### PR TITLE
Import of sauron-tail

### PR DESCRIPTION
**Pull request by zallison**
tail a file or process, optionall with filters

### CODE REVIEW

**Comment by djcb** [comment]
This would need some comment on how to get the `tail` package.

**Comment by zallison** [comment]
https://www.emacswiki.org/emacs/TailEl

The tail package has been included in the "emacs-goodies" in debian based distros, I believe it's in a similar package in redhat based distros.

**Comment by djcb** [comment]
Merged, thanks.

**Comment by zallison** [comment]
I've submitted an updated version, It's been improved over the past couple of years!

**Pull request merged**
